# Financial Fraud Detection Configuration

# --- DATA CONFIGURATION ---
data:
  # Veri dosya yolları (görece yollar)
  raw_data_path: "data/raw/Synthetic_Financial_datasets_log.csv"
  processed_data_path: "data/processed/"

  # Veri validasyon kuralları
  validation:
    required_columns: ["type", "amount", "isFraud", "nameOrig", "nameDest"]
    amount_min: 0
    class_values: [0, 1]
    missing_threshold: 0.1

  # Train/test split
  test_size: 0.3
  random_state: 42
  stratify: true

# --- PREPROCESSING CONFIGURATION ---
preprocessing:
  # Feature scaling
  scaling_method: "robust" #options: standard, robust, minmax

  # Categorical encodeing
  encoding_method: "onehot" #options: onehot, label, ordinal

  # Missing value handling
  numerical_imputation: "mean"
  categorical_imputation: "most_frequent"

  #Feature engineering
  create_balance_features: true

# --- IMBALANCE HANDLING ---
imbalance:
  method: "smote" #options: smote, adasyn, smotetomek, undersampling
  sampling_strategy: "auto"
  random_state: 42

# --- MODEL CONFIGURATION ---
models:
  #Random Forest
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
    class_weight: "balanced"

  #Logistic Regression
  logistic_regression:
    penalty: "l2"
    C: 1.0
    max_iter: 1000
    random_state: 42
    class_weight: "balanced"

  #Isolation Forest
  isolation_forest:
    contamination: 0.05
    n_estimators: 100
    max_samples: "auto"
    random_state: 42

# --- EVALUATION CONFIGURATION ---
evaluation:
  min_roc_auc: 0.90
  min_pr_auc: 0.3

# --- EXPLAINABILITY CONFIGURATION ---
explainability:
  shap:
    explainer_type: "tree"
    max_samples: 100